### PR TITLE
CI: Remove Node.js 7 and add 8 and 10.

### PR DESCRIPTION
**Pull request by XhmikosR**
Also remove the obsolete `sudo: false` from Travis.

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW we could probably use Travis for Windows testing too later, and see how it goes.

**Comment by jakubpawlowicz** [comment]
Good call :+1:, we probably should support v12 nowadays too?

**Comment by XhmikosR** [comment]
Yeah, but when I made the PR v12 wasn't LTS :)

IMO you should drop anything less than 8 and grab the chance to use modern features

**Comment by jakubpawlowicz** [comment]
Good idea :+1:

**Comment by XhmikosR** [comment]
I'm gonna take a stab at it in the next days, but please try to fix the Windows backslashes issue in source maps :)

**Pull request merged**
