### PR TITLE
fix proxy issues on https @imports

### LINKED ISSUE #741: Issues with proxied @import https urls
# Problem description

If you're using a http proxy the current implementation causes trouble and renders it completely unusable.

Example error:

```
File: assets/vendor.css
Broken @import declaration of "https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin" - write EPROTO
```

Gist: https://gist.github.com/wzrdtales/621ff62d38bb94737215

# Details

The failure is here;

https://github.com/jakubpawlowicz/clean-css/blob/master/lib/imports/inliner.js#L271-L273

This can't work and wont work if there is only a http proxy, but not a https one. And this is common for mostly all the time, to have just a http proxy.

# Possible solutions

Two options to fix this:

- Fix the check for http and https in combination with the proxy.
- Use the `request` lib instead

Using the `request` lib would be also be more convenient for the users, as it automatically parses `http_proxy` and `https_proxy` environment variables and handles many edge cases already. Thus the users never need to set any proxy configurations for `clean-css` if they are already defined them in their environment.

### PR DESCRIPTION
**Pull request by wzrdtales**
When an @import used a https url, the false protocol was tried to be used for the http proxy.

fixes #741

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
Is it possible to have some kind of integration test here, like ones in https://github.com/jakubpawlowicz/clean-css/blob/master/test/protocol-imports-test.js#L552 ?

**Comment by wzrdtales** [comment]
@jakubpawlowicz Sure thing, but as you have not had decided for one of the pull requests yet it would have been a waste of time to already add tests ;)

**Comment by jakubpawlowicz** [comment]
It's all good! Would you mind squashing all 3 commits into one? Then I'll merge the PR.

**Comment by wzrdtales** [comment]
I don't see any sense in that but okay, here you go.

**Comment by jakubpawlowicz** [comment]
It's to keep tests and code together so at some point it'd easier to figure out why this change was made. Thank you!

**Comment by wzrdtales** [comment]
ok, generally rewriting the git history is a bad thing though.

In which version is this going to be published?

**Comment by jakubpawlowicz** [comment]
Aiming at 3.4.11 tomorrow.

**Pull request merged**
