### PR TITLE
Fix input-source-map-tracker for node@6.*

### PR DESCRIPTION
**Pull request by nooks**

### CODE REVIEW

**Comment by neonexus** [comment]
Sure hopes this PR gets included soon. I've verified it works, and does make it Node v6 compatible.

**Comment by insanityfarm** [comment]
Seconding what @neonexus said. This fixed my build pipeline on Node 6. Thanks @nooks for your contribution!

**Comment by jakubpawlowicz** [comment]
Does this fix #769?

**Comment by nooks** [comment]
Yes

**Comment by jakubpawlowicz** [comment]
I can see it now: https://travis-ci.org/jakubpawlowicz/clean-css/jobs/132233238

**Comment by jakubpawlowicz** [comment]
Fixed in 3.4.13. Thanks!

**Comment by StealthyDev** [comment]
Is this fix available in the following release?

image

**Comment by jakubpawlowicz** [comment]
`npm ls clean-css` will tell you the version of clean-css you have

**Comment by JohnnyWalkerDesign** [comment]
I'm running:

└─┬ gulp-minify-css@1.2.4
  └── clean-css@3.4.10

But I can't see how to update to 3.4.14. `npm update clean-css` doesn't help.

**Comment by nlindroos** [comment]
Thanks @JohnnyWalkerDesign, installing `gulp-clean-css` and replacing `.minifyCss` with `.cleanCss` solved this for me.

**Pull request merged**
