### PR TITLE
Remove extra commas.

### PR DESCRIPTION
**Pull request by XhmikosR**
@jakubpawlowicz: how about distributing cleancss-browser.js too? I find it very useful instead of me having to check out the source and do it myself.

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
:+1:

**Comment by jakubpawlowicz** [comment]
Regarding `cleancss-browser.js` I'd rather avoid it as it's going to add some extra noise to the repo.

However I've been thinking recently about pulling out browserify support into a separate repo, where, in theory, `cleancss-browser.js` could be bundled and updated as necessary out of clean-css release cycle. Thoughts?

**Comment by XhmikosR** [comment]
I don't consider it bloat to be honest; it's just one file after all.

Your suggestion wouldn't solve the issue I describe either. We could just
have it run in the prepublish step for us or something similar.

**Comment by jakubpawlowicz** [comment]
Well, it's a just an overlay over clean-css and it's dependency tree is sth like a half of npm ;-) https://github.com/substack/node-browserify/blob/master/package.json#L22

What'd be the outcome of running it in prepublish step? I don''t see a point there.

**Comment by XhmikosR** [comment]
Well it would be sort of automated I guess.

Anyway, the key here is for the end user like myself not having to do the
whole process myself, especially when it's supported out of the box in this
repo. It's just one file (the npm dependencies isn't something I have to
care; I simply want the browser file)

**Comment by jakubpawlowicz** [comment]
I see the point but at the same time I don't want to pollute the repo with multiple browser builds. The easiest way would be to move it out to a dedicated repo.

**Comment by XhmikosR** [comment]
What multiple browsers builds? Just build it when you release a new version as part of bumping the version.

Your suggestion beats the point and is useless if the user has to check out yet another repo to get the file.

**Comment by jakubpawlowicz** [comment]
The repo should contain source files only, that's my point of view.

**Pull request merged**
