### PR TITLE
Travis: test node.js 0.12 too.

### PR DESCRIPTION
**Pull request by XhmikosR**
One test fails on Windows.

```console
> clean-css@3.1.0-pre test C:\Users\xmr\Desktop\clean-css
> vows

·······················  ·······················································
················································································
············ ···································································
················································································
················································································
················································································
················································································
················································································
················································································
················································································
················································································
················································································
················································································
················· ······························································
··············· ······································· ························
····································································· ··········
································ ································ ··············
·······································································✗ ·······
··········································· ········ ························ ··
·················· ·································· ········ ········· ······
········


    relative to path complex but partial input map referenced by path
      ✗ should have right sources
        » expected [ 'test/fixtures/source-maps/some.less', 'test/fixtures/source-maps/nested/once.less', 'test/fixtures/source-maps/styles.less' ],
        got      [ 'test\\fixtures\\source-maps\\some.less', 'test\\fixtures\\source-maps\\nested\\once.less', 'test\\fixtures\\source-maps\\styles.less' ] (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:892
  ✗ Broken » 1589 honored ∙ 1 broken (3.531s)
  ·✗npm ERR! Test failed.  See above for more details.

> C:\Users\xmr\Desktop\clean-css>node -v && npm -v
v0.12.0
2.5.1
```

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
Ah, path separators are different. Will fix, thanks :+1:

**Comment by XhmikosR** [comment]
BTW @jakubpawlowicz, how about adding AppVeyor for Windows testing? An example https://ci.appveyor.com/project/giakki/uncss/branch/master

**Comment by jakubpawlowicz** [comment]
Haven't came across it yet. Does it work well? Would be good to have CI testing Windows at some point too.

**Comment by XhmikosR** [comment]
@jakubpawlowicz: works pretty good, just a little slow some times, but generally OK.

Can you add it for this repo and add me as an owner until we set it up? Then just CC me to make a PR about this.

**Pull request merged**
