### PR TITLE
Add AppVeyor for Windows tests.

### PR DESCRIPTION
**Pull request by XhmikosR**
WIP until @jakubpawlowicz you add AppVeyor for the repository itself :)

Also, note that node.js 0.12 hasn't been deployed yet on AppVeyor. I have notified @FeodorFitsner so it shouldn't take long before it's been added.

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
@XhmikosR I've created AppVeyor account and added clean-css to it - https://ci.appveyor.com/project/jakubpawlowicz/clean-css 

Should we rather merge this PR into a branch to find out if config is OK?

**Comment by XhmikosR** [comment]
Nah, no need for another branch  https://ci.appveyor.com/project/jakubpawlowicz/clean-css/build/2

Please enable the option via the web interface to skip branches without appveyor.yml though.

**Comment by XhmikosR** [comment]
So, everything looks good so far. We'll test caching after tests pass. So, you can merge this unless you want to fix the broken test first and I rebase then.

**Comment by jakubpawlowicz** [comment]
Seems to work well, thanks! :+1:

**Comment by XhmikosR** [comment]
Cool! Feel free to add io.js for Travis too.

**Pull request merged**
