### PR TITLE
Bump source-map to 0.3.x.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jakubpawlowicz: don't merge this yet, I'll see if I can solve the failures.

**Comment by jakubpawlowicz** [comment]
Sure, let me know how it goes, otherwise I'll do.

For dep version you can use `0.3.x` - the only reason I used `>=0.1.43` is that `source-map` changed their internal API in that version.

**Comment by XhmikosR** [comment]
Something is fishy with the paths... I get 21 test failures on Windows with node.js 0.12 while Travis gets 26 :/

```

> clean-css@3.1.0-pre test C:\Users\xmr\Desktop\clean-css
> vows

·······················  ··················································································································································· ·························································································································································································································································································································································································································································································································································································································································································································································································································································································································· ················ ············································································· ······································· ····························································································· ·········································· ································· ······························✗··✗··✗··✗·✗···✗··✗·✗··✗···✗✗✗·✗✗✗✗···✗··········✗✗·✗··✗ ·················································· ········ ························ ···················· ·································· ········ ········· ······ ········


    input map as string
      ✗ should have selector mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 4,
      source: 'styles.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:321

    input map from source
      ✗ should have selector mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 4,
      source: 'styles.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:349

    input map from source with root
      ✗ should have selector mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 4,
      source: 'styles.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:377

    complex input map
      ✗ should have first selector mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: 'some.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: '\\some.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:405

      ✗ should have second selector mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 14,
      originalLine: 1,
      originalColumn: 4,
      source: 'styles.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 14,
      originalLine: 1,
      originalColumn: 0,
      source: '\\styles.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:427

    complex but partial input map referenced by path
      ✗ should have 2 mappings to .less file
        » expected [
      {
          generatedLine: 1,
          generatedColumn: 6,
          originalLine: 2,
          originalColumn: 2,
          source: 'test\\fixtures\\source-maps\\styles.less',
          name: null
      }
  ] to have 2 element(s) // assert.js:54

    complex input map with an existing file as target
      ✗ should have 2 mappings to styles.less file
        » expected [
      {
          generatedLine: 1,
          generatedColumn: 6,
          originalLine: 2,
          originalColumn: 2,
          source: 'styles.less',
          name: null
      }
  ] to have 2 element(s) // assert.js:54

    nested once
      ✗ should have "section > div a" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 2,
      originalColumn: 8,
      source: 'once.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: 'C:\\Users\\xmr\\Desktop\\clean-css\\test\\fixtures\\source-maps\\nested\\once.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:491

    nested twice
      ✗ should have "body > nav a" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 3,
      originalColumn: 4,
      source: 'twice.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: 'C:\\Users\\xmr\\Desktop\\clean-css\\test\\fixtures\\source-maps\\nested\\twice.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:519

    input source map with missing mutliselector input
      ✗ should have "a:hover" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 2,
      originalLine: 1,
      originalColumn: 0,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 2,
      originalLine: 2,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:558

      ✗ should have "a:visited" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 10,
      originalLine: 1,
      originalColumn: 0,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 10,
      originalLine: 3,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:569

      ✗ should have "color:red" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 20,
      originalLine: 5,
      originalColumn: 4,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 20,
      originalLine: 5,
      originalColumn: 15,
      source: 'source.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:580

    input source map with missing mutliselector sortable input
      ✗ should have "a.button:hover" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 3,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:597

      ✗ should have "a.button:link" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 15,
      originalLine: 1,
      originalColumn: 0,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 15,
      originalLine: 1,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:608

      ✗ should have "a.button:visited" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 29,
      originalLine: 1,
      originalColumn: 0,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 29,
      originalLine: 2,
      originalColumn: 0,
      source: '__stdin__.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:619

      ✗ should have "color:red" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 46,
      originalLine: 5,
      originalColumn: 4,
      source: 'source.css',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 46,
      originalLine: 5,
      originalColumn: 15,
      source: 'source.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:630

    absolute source map from external host via http
      ✗ maps to external source file
        »
        actual expected

        http://127.0.0.1/remotestyles.cssless
         // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:703

    multiple source maps relative to local
      ✗ should have "div" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: 'some.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 0,
      originalLine: 1,
      originalColumn: 0,
      source: 'C:\\Users\\xmr\\Desktop\\clean-css\\test\\fixtures\\source-maps\\some.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:818

      ✗ should have "section > div a" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 4,
      originalLine: 2,
      originalColumn: 8,
      source: 'once.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 4,
      originalLine: 1,
      originalColumn: 0,
      source: 'C:\\Users\\xmr\\Desktop\\clean-css\\test\\fixtures\\source-maps\\nested\\once.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:829

      ✗ should have "div > a" mapping
        » expected {
      generatedLine: 1,
      generatedColumn: 28,
      originalLine: 1,
      originalColumn: 4,
      source: 'styles.less',
      name: null
  },
  	got	 {
      generatedLine: 1,
      generatedColumn: 28,
      originalLine: 1,
      originalColumn: 0,
      source: 'C:\\Users\\xmr\\Desktop\\clean-css\\test\\fixtures\\source-maps\\styles.css',
      name: null
  } (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:851

    relative to path complex but partial input map referenced by path
      ✗ should have right sources
        » expected [ 'test/fixtures/source-maps/some.less', 'test/fixtures/source-maps/nested/once.less', 'test/fixtures/source-maps/styles.less' ],
  	got	 [
      'test\\fixtures\\source-maps\\some.css',
      'test\\fixtures\\source-maps\\nested\\once.css',
      'test\\fixtures\\source-maps\\some.less',
      'test\\fixtures\\source-maps\\styles.css',
      'test\\fixtures\\source-maps\\styles.less'
  ] (deepEqual) // C:\Users\xmr\Desktop\clean-css\test\source-map-test.js:892
  ✗ Broken » 1592 honored ∙ 21 broken (1.375s)
  ·✗
```

We need to merge #458, which is basically ready, I only wait from you to add AppVeyor for this repo.

**Comment by jakubpawlowicz** [comment]
Something is indeed, I'll take a look later today.

**Comment by XhmikosR** [comment]
I'll close this and let you make the update yourself @jakubpawlowicz. Something has changed upstream.

**Pull request closed without merging**
