### PR TITLE
+ online tools

### LINKED ISSUE #330: Web interface
@GoalSmashers: Since clean-css can be successfully used as a web module, how about we make use of GitHub pages and provide a web interface? It doesn't need to be fancy at first, just a working solution.

### PR DESCRIPTION
**Pull request by tomByrer**
closes #330

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
Could you please rename the heading to "How to use clean-css from a web browser?" - that way it'll match the "build tools" section above.

**Comment by tomByrer** [comment]
That makes more sense.

**Comment by jakubpawlowicz** [comment]
:+1:

**Comment by tomByrer** [comment]
cheers

**Pull request merged**
