### PR TITLE
Fix identifier regex to allow for leading underscores

### LINKED ISSUE #1056: Identifier with starting underscore considered incorrect
### Environment

Online tool

### Configuration options

Level 2, merge semantically, remove unused @ at rules, restructure rules

### Input CSS

```css
@keyframes _loading {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.load {
  animation: _loading 8s steps(8) infinite;
}
```

### Actual output CSS

Empty

### Expected output CSS

```css
@keyframes _loading{from{transform:rotate(0)}to{transform:rotate(360deg)}}.load{animation:8s steps(8) infinite _loading}
```
### Explanation

If we change animation name from `_loading` to `loading`, then everything works as expected. So it seems that the animation identifier with starting underscore is considered incorrect. However, it is correct according to [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident#Examples).
As far as I understand, problem can be solved by fixing `identifierRegex` in lib/optimizer/validator.js

### PR DESCRIPTION
**Pull request by kennygoff**
This will fix the identifier checks for animations to allow for names with leading underscores, as well as `_` by itself. Both should be valid according to MDN

See: https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident

Fixes #1056

### CODE REVIEW

**Comment by jakubpawlowicz** [comment]
:+1: for having it - would you mind adding a simple test in https://github.com/jakubpawlowicz/clean-css/blob/master/test/integration-test.js ?

**Comment by kennygoff** [comment]
Wasn't sure where in the integration test it made sense. I had issues with `break-up` failing so I added a test there. If there's other areas that need testing let me know and I can add more!

**Comment by mikolalysenko** [comment]
This problem is very common when applying clean-css to the output of post-css.

**Comment by jakubpawlowicz** [comment]
:+1: I've just merged it manually (due to some codebase changes) and it will be released soon in clean-css 5.0. Thanks for your patience.

**Pull request closed without merging**
